version: '3.8'

services:
  rpa-mit-approvals-seedprovider:
    build:
      target: development
    ports:
      - "3000:3000"
    volumes:

  rpa-mit-approvals-seedprovider-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: