version: '3.8'

services:
  rpa-mit-approvals-seed-provider:
    build:
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./EST.MIT.Approvals.SeedProvider:/home/dotnet/EST.MIT.Approvals.SeedProvider
      
  rpa-mit-approvals-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: